FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY DockerASPNET/DockerASPNET.csproj, DockerASPNET/
RUN dotnet restore DockerASPNET/DockerASPNET.csproj
COPY . .
WORKDIR /src/DockerASPNET
RUN dotnet build DockerASPNET.csproj -c Release -o /app/build

FROM build AS publish
RUN dotnet publish DockerASPNET.csproj -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "DockerASPNET.dll"]